### ISSUE TITLE
caddy failing on redeploy + upgrade due to letsencrypt rate limit

### ISSUE THREAD

**Issue by drnic** [govau/instant-https-boshrelease#16]
@aeijdenberg sorry to ping on a weekend; but perhaps you can spot why this might happening.

I did a harmless update of v0.4.0 to update the stemcell; and the deploy failed. I then upgraded to v4.2.0 and the logs show:

```
==> /var/vcap/sys/log/proxy/caddy.stderr <==
2018/03/10 02:36:25 [ci-ohio.starkandwayne.com] failed to get certificate: acme: Error 429 - urn:acme:error:rateLimited - Error creating new cert :: too many certificates already issued for exact set of domains: ci-ohio.starkandwayne.com: see https://letsencrypt.org/docs/rate-limits/
```
Have you seen this before; and suggest remedy?

**Comment by drnic** [comment]
In the meantime, I've switched to a different subdomain and letsencrypt seems happy with that, but its sad about `ci-ohio.starkandwayne.com`

**Comment by sarneaud** [comment]
It's easy to hit the limits if you do multiple deployments during development/testing when using the production API.  (Normal updates should be okay though.)  I think the only remedy is trying to use the staging API as much as possible during dev (`acme_url` property).

**Comment by drnic** [comment]
I wish I'd seen the original error when I was just bumping the stemcell. I hadn't touched the deployment in ages.

I'll close this as its not a bug in this release so much as a confusion about caddy + letsencrypt which resulting in forcing me to change URLs without knowing how to resolve the issue at a moment of urgency.

Thanks @sarneaud for the idea on alternate `acme_url`. I'm not sure I would have though "update stemcell" would require me to change the acme_url. I'm still unsure how I would have prevented this issue; so I'm now gun shy of using letsencrypt :/

**Comment by aeijdenberg** [comment]
Hi @drnic - I think we probably need to modify this release such that the key and cert are written to non-emphemeral storage (I'm not sure the easiest way to do so in `bosh`).

As it stands a new cert is requested each time the instance is recreated and eventually Let's Encrypt  rate limits that will kick in.

As @sarneaud mentions, we did used to hit this a bit when using this release. I have not seen that issue occur in our other usages of Let's Encrypt, where we persist keys/certs, and renew 30 days out.

**Comment by aeijdenberg** [comment]
Btw, @drnic , if it's helpful, you can see all of the certificates that were issued for that domain here: https://crt.sh/?q=ci-ohio.starkandwayne.com - ie there look to be around 8 issued during the past week.

**Comment by drnic** [comment]
adam - the non-ephemeral storage is the simple part in bosh right? just
store it in /var/vcap/store/instance-https or similar? Or is it a different
problem you're thinking of?

**Comment by aeijdenberg** [comment]
@drnic - yes that is I think what I'm thinking of. It probably is an easy fix - I just haven't had an opportunity to take the time to look where Caddy is storing this data, and move it to somewhere that persists (and I haven't done that in `bosh` before).
